jekyll:
    image: jekyll/jekyll:latest
    command: bash -c "touch Gemfile.lock && chmod a+w Gemfile.lock && chmod -R 777 _data/ && chmod -R 777 _pages/ && chmod -R 777 _site/ && jekyll build"
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll