jekyll:
    image: jekyll/jekyll:latest
    command: bash -c "touch Gemfile.lock && chmod a+w Gemfile.lock && chmod a+w _data/_news/config.yaml && jekyll build"
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll